# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from numpy import array, sqrt, sin, cos, deg2rad, rad2deg, arctan2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("satellite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input = QtWidgets.QGroupBox(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(10, 10, 401, 661))
        self.input.setAlignment(QtCore.Qt.AlignCenter)
        self.input.setFlat(True)
        self.input.setCheckable(False)
        self.input.setObjectName("input")
        self.label = QtWidgets.QLabel(self.input)
        self.label.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.label.setObjectName("label")
        self.beta = QtWidgets.QLineEdit(self.input)
        self.beta.setGeometry(QtCore.QRect(140, 40, 81, 20))
        self.beta.setObjectName("beta")
        self.label_2 = QtWidgets.QLabel(self.input)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.input)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 101, 16))
        self.label_3.setObjectName("label_3")
        self.begin_time = QtWidgets.QComboBox(self.input)
        self.begin_time.setGeometry(QtCore.QRect(140, 150, 69, 22))
        self.begin_time.setObjectName("begin_time")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.begin_time.addItem("")
        self.end_time = QtWidgets.QComboBox(self.input)
        self.end_time.setGeometry(QtCore.QRect(140, 190, 69, 22))
        self.end_time.setObjectName("end_time")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.end_time.addItem("")
        self.time_frame = QtWidgets.QFrame(self.input)
        self.time_frame.setGeometry(QtCore.QRect(10, 90, 311, 141))
        self.time_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.time_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.time_frame.setObjectName("time_frame")
        self.label_15 = QtWidgets.QLabel(self.time_frame)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.label_15.setObjectName("label_15")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.time_frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 10, 21, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.time_frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 10, 31, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.time_frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(270, 10, 31, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_16 = QtWidgets.QLabel(self.time_frame)
        self.label_16.setGeometry(QtCore.QRect(120, 10, 16, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.time_frame)
        self.label_17.setGeometry(QtCore.QRect(170, 10, 16, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.time_frame)
        self.label_18.setGeometry(QtCore.QRect(230, 10, 31, 16))
        self.label_18.setObjectName("label_18")
        self.beta_frame = QtWidgets.QFrame(self.input)
        self.beta_frame.setGeometry(QtCore.QRect(10, 30, 311, 41))
        self.beta_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.beta_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.beta_frame.setObjectName("beta_frame")
        self.of_dialog = QtWidgets.QPushButton(self.input)
        self.of_dialog.setGeometry(QtCore.QRect(20, 430, 91, 23))
        self.of_dialog.setObjectName("of_dialog")
        self.label_4 = QtWidgets.QLabel(self.input)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 101, 16))
        self.label_4.setObjectName("label_4")
        self.base_station = QtWidgets.QComboBox(self.input)
        self.base_station.setGeometry(QtCore.QRect(140, 260, 51, 22))
        self.base_station.setObjectName("base_station")
        self.base_station.addItem("")
        self.base_station.setItemText(0, "")
        self.base_station.addItem("")
        self.base_station.addItem("")
        self.frame = QtWidgets.QFrame(self.input)
        self.frame.setGeometry(QtCore.QRect(10, 250, 311, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(240, 50, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(240, 80, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(240, 110, 47, 13))
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(self.input)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(50, 470, 261, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.latit = QtWidgets.QLineEdit(self.input)
        self.latit.setEnabled(False)
        self.latit.setGeometry(QtCore.QRect(130, 300, 113, 20))
        self.latit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.latit.setObjectName("latit")
        self.longit = QtWidgets.QLineEdit(self.input)
        self.longit.setEnabled(False)
        self.longit.setGeometry(QtCore.QRect(130, 330, 113, 20))
        self.longit.setObjectName("longit")
        self.height = QtWidgets.QLineEdit(self.input)
        self.height.setEnabled(False)
        self.height.setGeometry(QtCore.QRect(130, 360, 113, 20))
        self.height.setObjectName("height")
        self.label_5 = QtWidgets.QLabel(self.input)
        self.label_5.setGeometry(QtCore.QRect(60, 250, 47, 13))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.input)
        self.label_6.setGeometry(QtCore.QRect(60, 330, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.input)
        self.label_7.setGeometry(QtCore.QRect(60, 360, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.input)
        self.label_8.setGeometry(QtCore.QRect(60, 300, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.input)
        self.label_9.setGeometry(QtCore.QRect(20, 470, 47, 20))
        self.label_9.setObjectName("label_9")
        self.frame_2 = QtWidgets.QFrame(self.input)
        self.frame_2.setGeometry(QtCore.QRect(10, 420, 311, 191))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(10, 130, 91, 16))
        self.label_13.setObjectName("label_13")
        self.sp3date = QtWidgets.QLineEdit(self.frame_2)
        self.sp3date.setEnabled(False)
        self.sp3date.setGeometry(QtCore.QRect(100, 130, 113, 20))
        self.sp3date.setObjectName("sp3date")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 90, 21, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.input)
        self.pushButton.setGeometry(QtCore.QRect(10, 630, 111, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.frame_2.raise_()
        self.frame.raise_()
        self.beta_frame.raise_()
        self.time_frame.raise_()
        self.label.raise_()
        self.beta.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.begin_time.raise_()
        self.end_time.raise_()
        self.of_dialog.raise_()
        self.label_4.raise_()
        self.base_station.raise_()
        self.lineEdit.raise_()
        self.latit.raise_()
        self.longit.raise_()
        self.height.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.pushButton.raise_()
        self.results = QtWidgets.QGroupBox(self.centralwidget)
        self.results.setGeometry(QtCore.QRect(430, 10, 571, 661))
        self.results.setAlignment(QtCore.Qt.AlignCenter)
        self.results.setFlat(True)
        self.results.setObjectName("results")
        self.textBrowser = QtWidgets.QTextBrowser(self.results)
        self.textBrowser.setGeometry(QtCore.QRect(30, 30, 531, 581))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Occupation Planning"))
        self.input.setTitle(_translate("MainWindow", "Input Data"))
        self.label.setText(_translate("MainWindow", "Minimum Beta Angle:"))
        self.label_2.setText(_translate("MainWindow", "Select Beginning Time:"))
        self.label_3.setText(_translate("MainWindow", "Select End Time:"))
        self.begin_time.setItemText(0, _translate("MainWindow", "00:00"))
        self.begin_time.setItemText(1, _translate("MainWindow", "00:15"))
        self.begin_time.setItemText(2, _translate("MainWindow", "00:30"))
        self.begin_time.setItemText(3, _translate("MainWindow", "00:45"))
        self.begin_time.setItemText(4, _translate("MainWindow", "01:00"))
        self.begin_time.setItemText(5, _translate("MainWindow", "01:15"))
        self.begin_time.setItemText(6, _translate("MainWindow", "01:30"))
        self.begin_time.setItemText(7, _translate("MainWindow", "01:45"))
        self.begin_time.setItemText(8, _translate("MainWindow", "02:00"))
        self.begin_time.setItemText(9, _translate("MainWindow", "02:15"))
        self.begin_time.setItemText(10, _translate("MainWindow", "02:30"))
        self.begin_time.setItemText(11, _translate("MainWindow", "02:45"))
        self.begin_time.setItemText(12, _translate("MainWindow", "03:00"))
        self.begin_time.setItemText(13, _translate("MainWindow", "03:15"))
        self.begin_time.setItemText(14, _translate("MainWindow", "03:30"))
        self.begin_time.setItemText(15, _translate("MainWindow", "03:45"))
        self.begin_time.setItemText(16, _translate("MainWindow", "04:00"))
        self.begin_time.setItemText(17, _translate("MainWindow", "04:15"))
        self.begin_time.setItemText(18, _translate("MainWindow", "04:30"))
        self.begin_time.setItemText(19, _translate("MainWindow", "04:45"))
        self.begin_time.setItemText(20, _translate("MainWindow", "05:00"))
        self.begin_time.setItemText(21, _translate("MainWindow", "05:15"))
        self.begin_time.setItemText(22, _translate("MainWindow", "05:30"))
        self.begin_time.setItemText(23, _translate("MainWindow", "05:45"))
        self.begin_time.setItemText(24, _translate("MainWindow", "06:00"))
        self.begin_time.setItemText(25, _translate("MainWindow", "06:15"))
        self.begin_time.setItemText(26, _translate("MainWindow", "06:30"))
        self.begin_time.setItemText(27, _translate("MainWindow", "06:45"))
        self.begin_time.setItemText(28, _translate("MainWindow", "07:00"))
        self.begin_time.setItemText(29, _translate("MainWindow", "07:15"))
        self.begin_time.setItemText(30, _translate("MainWindow", "07:30"))
        self.begin_time.setItemText(31, _translate("MainWindow", "07:45"))
        self.begin_time.setItemText(32, _translate("MainWindow", "08:00"))
        self.begin_time.setItemText(33, _translate("MainWindow", "08:15"))
        self.begin_time.setItemText(34, _translate("MainWindow", "08:30"))
        self.begin_time.setItemText(35, _translate("MainWindow", "08:45"))
        self.begin_time.setItemText(36, _translate("MainWindow", "09:00"))
        self.begin_time.setItemText(37, _translate("MainWindow", "09:15"))
        self.begin_time.setItemText(38, _translate("MainWindow", "09:30"))
        self.begin_time.setItemText(39, _translate("MainWindow", "09:45"))
        self.begin_time.setItemText(40, _translate("MainWindow", "10:00"))
        self.begin_time.setItemText(41, _translate("MainWindow", "10:15"))
        self.begin_time.setItemText(42, _translate("MainWindow", "10:30"))
        self.begin_time.setItemText(43, _translate("MainWindow", "10:45"))
        self.begin_time.setItemText(44, _translate("MainWindow", "11:00"))
        self.begin_time.setItemText(45, _translate("MainWindow", "11:15"))
        self.begin_time.setItemText(46, _translate("MainWindow", "11:30"))
        self.begin_time.setItemText(47, _translate("MainWindow", "11:45"))
        self.begin_time.setItemText(48, _translate("MainWindow", "12:00"))
        self.begin_time.setItemText(49, _translate("MainWindow", "12:15"))
        self.begin_time.setItemText(50, _translate("MainWindow", "12:30"))
        self.begin_time.setItemText(51, _translate("MainWindow", "12:45"))
        self.begin_time.setItemText(52, _translate("MainWindow", "13:00"))
        self.begin_time.setItemText(53, _translate("MainWindow", "13:15"))
        self.begin_time.setItemText(54, _translate("MainWindow", "13:30"))
        self.begin_time.setItemText(55, _translate("MainWindow", "13:45"))
        self.begin_time.setItemText(56, _translate("MainWindow", "14:00"))
        self.begin_time.setItemText(57, _translate("MainWindow", "14:15"))
        self.begin_time.setItemText(58, _translate("MainWindow", "14:30"))
        self.begin_time.setItemText(59, _translate("MainWindow", "14:45"))
        self.begin_time.setItemText(60, _translate("MainWindow", "15:00"))
        self.begin_time.setItemText(61, _translate("MainWindow", "15:15"))
        self.begin_time.setItemText(62, _translate("MainWindow", "15:30"))
        self.begin_time.setItemText(63, _translate("MainWindow", "15:45"))
        self.begin_time.setItemText(64, _translate("MainWindow", "16:00"))
        self.begin_time.setItemText(65, _translate("MainWindow", "16:15"))
        self.begin_time.setItemText(66, _translate("MainWindow", "16:30"))
        self.begin_time.setItemText(67, _translate("MainWindow", "16:45"))
        self.begin_time.setItemText(68, _translate("MainWindow", "17:00"))
        self.begin_time.setItemText(69, _translate("MainWindow", "17:15"))
        self.begin_time.setItemText(70, _translate("MainWindow", "17:30"))
        self.begin_time.setItemText(71, _translate("MainWindow", "17:45"))
        self.begin_time.setItemText(72, _translate("MainWindow", "18:00"))
        self.begin_time.setItemText(73, _translate("MainWindow", "18:15"))
        self.begin_time.setItemText(74, _translate("MainWindow", "18:30"))
        self.begin_time.setItemText(75, _translate("MainWindow", "18:45"))
        self.begin_time.setItemText(76, _translate("MainWindow", "19:00"))
        self.begin_time.setItemText(77, _translate("MainWindow", "19:15"))
        self.begin_time.setItemText(78, _translate("MainWindow", "19:30"))
        self.begin_time.setItemText(79, _translate("MainWindow", "19:45"))
        self.begin_time.setItemText(80, _translate("MainWindow", "20:00"))
        self.begin_time.setItemText(81, _translate("MainWindow", "20:15"))
        self.begin_time.setItemText(82, _translate("MainWindow", "20:30"))
        self.begin_time.setItemText(83, _translate("MainWindow", "20:45"))
        self.begin_time.setItemText(84, _translate("MainWindow", "21:00"))
        self.begin_time.setItemText(85, _translate("MainWindow", "21:15"))
        self.begin_time.setItemText(86, _translate("MainWindow", "21:30"))
        self.begin_time.setItemText(87, _translate("MainWindow", "21:45"))
        self.begin_time.setItemText(88, _translate("MainWindow", "22:00"))
        self.begin_time.setItemText(89, _translate("MainWindow", "22:15"))
        self.begin_time.setItemText(90, _translate("MainWindow", "22:30"))
        self.begin_time.setItemText(91, _translate("MainWindow", "22:45"))
        self.begin_time.setItemText(92, _translate("MainWindow", "23:00"))
        self.begin_time.setItemText(93, _translate("MainWindow", "23:15"))
        self.begin_time.setItemText(94, _translate("MainWindow", "23:30"))
        self.begin_time.setItemText(95, _translate("MainWindow", "23:45"))
        self.end_time.setItemText(0, _translate("MainWindow", "00:00"))
        self.end_time.setItemText(1, _translate("MainWindow", "00:15"))
        self.end_time.setItemText(2, _translate("MainWindow", "00:30"))
        self.end_time.setItemText(3, _translate("MainWindow", "00:45"))
        self.end_time.setItemText(4, _translate("MainWindow", "01:00"))
        self.end_time.setItemText(5, _translate("MainWindow", "01:15"))
        self.end_time.setItemText(6, _translate("MainWindow", "01:30"))
        self.end_time.setItemText(7, _translate("MainWindow", "01:45"))
        self.end_time.setItemText(8, _translate("MainWindow", "02:00"))
        self.end_time.setItemText(9, _translate("MainWindow", "02:15"))
        self.end_time.setItemText(10, _translate("MainWindow", "02:30"))
        self.end_time.setItemText(11, _translate("MainWindow", "02:45"))
        self.end_time.setItemText(12, _translate("MainWindow", "03:00"))
        self.end_time.setItemText(13, _translate("MainWindow", "03:15"))
        self.end_time.setItemText(14, _translate("MainWindow", "03:30"))
        self.end_time.setItemText(15, _translate("MainWindow", "03:45"))
        self.end_time.setItemText(16, _translate("MainWindow", "04:00"))
        self.end_time.setItemText(17, _translate("MainWindow", "04:15"))
        self.end_time.setItemText(18, _translate("MainWindow", "04:30"))
        self.end_time.setItemText(19, _translate("MainWindow", "04:45"))
        self.end_time.setItemText(20, _translate("MainWindow", "05:00"))
        self.end_time.setItemText(21, _translate("MainWindow", "05:15"))
        self.end_time.setItemText(22, _translate("MainWindow", "05:30"))
        self.end_time.setItemText(23, _translate("MainWindow", "05:45"))
        self.end_time.setItemText(24, _translate("MainWindow", "06:00"))
        self.end_time.setItemText(25, _translate("MainWindow", "06:15"))
        self.end_time.setItemText(26, _translate("MainWindow", "06:30"))
        self.end_time.setItemText(27, _translate("MainWindow", "06:45"))
        self.end_time.setItemText(28, _translate("MainWindow", "07:00"))
        self.end_time.setItemText(29, _translate("MainWindow", "07:15"))
        self.end_time.setItemText(30, _translate("MainWindow", "07:30"))
        self.end_time.setItemText(31, _translate("MainWindow", "07:45"))
        self.end_time.setItemText(32, _translate("MainWindow", "08:00"))
        self.end_time.setItemText(33, _translate("MainWindow", "08:15"))
        self.end_time.setItemText(34, _translate("MainWindow", "08:30"))
        self.end_time.setItemText(35, _translate("MainWindow", "08:45"))
        self.end_time.setItemText(36, _translate("MainWindow", "09:00"))
        self.end_time.setItemText(37, _translate("MainWindow", "09:15"))
        self.end_time.setItemText(38, _translate("MainWindow", "09:30"))
        self.end_time.setItemText(39, _translate("MainWindow", "09:45"))
        self.end_time.setItemText(40, _translate("MainWindow", "10:00"))
        self.end_time.setItemText(41, _translate("MainWindow", "10:15"))
        self.end_time.setItemText(42, _translate("MainWindow", "10:30"))
        self.end_time.setItemText(43, _translate("MainWindow", "10:45"))
        self.end_time.setItemText(44, _translate("MainWindow", "11:00"))
        self.end_time.setItemText(45, _translate("MainWindow", "11:15"))
        self.end_time.setItemText(46, _translate("MainWindow", "11:30"))
        self.end_time.setItemText(47, _translate("MainWindow", "11:45"))
        self.end_time.setItemText(48, _translate("MainWindow", "12:00"))
        self.end_time.setItemText(49, _translate("MainWindow", "12:15"))
        self.end_time.setItemText(50, _translate("MainWindow", "12:30"))
        self.end_time.setItemText(51, _translate("MainWindow", "12:45"))
        self.end_time.setItemText(52, _translate("MainWindow", "13:00"))
        self.end_time.setItemText(53, _translate("MainWindow", "13:15"))
        self.end_time.setItemText(54, _translate("MainWindow", "13:30"))
        self.end_time.setItemText(55, _translate("MainWindow", "13:45"))
        self.end_time.setItemText(56, _translate("MainWindow", "14:00"))
        self.end_time.setItemText(57, _translate("MainWindow", "14:15"))
        self.end_time.setItemText(58, _translate("MainWindow", "14:30"))
        self.end_time.setItemText(59, _translate("MainWindow", "14:45"))
        self.end_time.setItemText(60, _translate("MainWindow", "15:00"))
        self.end_time.setItemText(61, _translate("MainWindow", "15:15"))
        self.end_time.setItemText(62, _translate("MainWindow", "15:30"))
        self.end_time.setItemText(63, _translate("MainWindow", "15:45"))
        self.end_time.setItemText(64, _translate("MainWindow", "16:00"))
        self.end_time.setItemText(65, _translate("MainWindow", "16:15"))
        self.end_time.setItemText(66, _translate("MainWindow", "16:30"))
        self.end_time.setItemText(67, _translate("MainWindow", "16:45"))
        self.end_time.setItemText(68, _translate("MainWindow", "17:00"))
        self.end_time.setItemText(69, _translate("MainWindow", "17:15"))
        self.end_time.setItemText(70, _translate("MainWindow", "17:30"))
        self.end_time.setItemText(71, _translate("MainWindow", "17:45"))
        self.end_time.setItemText(72, _translate("MainWindow", "18:00"))
        self.end_time.setItemText(73, _translate("MainWindow", "18:15"))
        self.end_time.setItemText(74, _translate("MainWindow", "18:30"))
        self.end_time.setItemText(75, _translate("MainWindow", "18:45"))
        self.end_time.setItemText(76, _translate("MainWindow", "19:00"))
        self.end_time.setItemText(77, _translate("MainWindow", "19:15"))
        self.end_time.setItemText(78, _translate("MainWindow", "19:30"))
        self.end_time.setItemText(79, _translate("MainWindow", "19:45"))
        self.end_time.setItemText(80, _translate("MainWindow", "20:00"))
        self.end_time.setItemText(81, _translate("MainWindow", "20:15"))
        self.end_time.setItemText(82, _translate("MainWindow", "20:30"))
        self.end_time.setItemText(83, _translate("MainWindow", "20:45"))
        self.end_time.setItemText(84, _translate("MainWindow", "21:00"))
        self.end_time.setItemText(85, _translate("MainWindow", "21:15"))
        self.end_time.setItemText(86, _translate("MainWindow", "21:30"))
        self.end_time.setItemText(87, _translate("MainWindow", "21:45"))
        self.end_time.setItemText(88, _translate("MainWindow", "22:00"))
        self.end_time.setItemText(89, _translate("MainWindow", "22:15"))
        self.end_time.setItemText(90, _translate("MainWindow", "22:30"))
        self.end_time.setItemText(91, _translate("MainWindow", "22:45"))
        self.end_time.setItemText(92, _translate("MainWindow", "23:00"))
        self.end_time.setItemText(93, _translate("MainWindow", "23:15"))
        self.end_time.setItemText(94, _translate("MainWindow", "23:30"))
        self.end_time.setItemText(95, _translate("MainWindow", "23:45"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Select Beginning</p><p>           Date:</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "dd"))
        self.label_17.setText(_translate("MainWindow", "mm"))
        self.label_18.setText(_translate("MainWindow", "yyyy"))
        self.of_dialog.setText(_translate("MainWindow", "Browse SP3 file"))
        self.label_4.setText(_translate("MainWindow", "Select Base Station:"))
        self.base_station.setItemText(1, _translate("MainWindow", "BSHM"))
        self.base_station.setItemText(2, _translate("MainWindow", "ELAT"))
        self.label_10.setText(_translate("MainWindow", "DMS"))
        self.label_11.setText(_translate("MainWindow", "DMS"))
        self.label_12.setText(_translate("MainWindow", "meters"))
        self.label_6.setText(_translate("MainWindow", "Longitude:"))
        self.label_7.setText(_translate("MainWindow", "Height:"))
        self.label_8.setText(_translate("MainWindow", "Latitude:"))
        self.label_9.setText(_translate("MainWindow", "Path:"))
        self.label_13.setText(_translate("MainWindow", "Date for this SP3:"))
        self.label_14.setText(_translate("MainWindow", "#Satellites:"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.results.setTitle(_translate("MainWindow", "Results"))
        self.of_dialog.clicked.connect(self.openfile)
        self.base_station.currentTextChanged.connect(self.basestation_comb)

    def basestation_comb(self, value):
        if value == '':
            self.latit.setText('')
            self.longit.setText('')
            self.height.setText('')

        if value == 'BSHM':
            self.latit.setText('''32°46'44.34472"''')
            self.longit.setText('''35°1'22.74061"''')
            self.height.setText('225.046')
            b_station = [array([deg2rad(32+46/60+44.34472/3600), deg2rad(35+1/60+22.74061/3600), 225.046])]

        if value == 'ELAT':
            self.latit.setText('''29°30'33.40506"''')
            self.longit.setText('''34°55'14.16064"''')
            self.height.setText('29.521')
            b_station = [
                array([deg2rad(29 + 30 / 60 + 33.40506 / 3600), deg2rad(34 + 55 / 60 + 14.16064 / 3600), 29.521])]


    def openfile(self):
        fname = QFileDialog.getOpenFileName(None, "Open data file", '.', "(*.sp3)")
        #file = open(fname[0], 'r')
        with open(fname[0], 'r') as file:
            lines = file.readlines()
            self.lineEdit.setText(fname[0])
            self.lineEdit_2.setText(lines[2].split()[1])
            begin_time = self.begin_time.currentText().split(':')
            end_time = self.end_time.currentText().split(':')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
